import { Sidebar } from '@/components/sidebar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="flex">
        <Sidebar />
        <div className="flex flex-col gap-2 w-full min-h-screen bg-accent">
          {children}
        </div>
      </body>
    </html>
  )
}
